<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HP-PC" ignored="0" name="Chrome Test" tests="11" failures="1" timestamp="02 Jun 2019 20:17:01 GMT" time="44.358" errors="0">
  <testcase name="testCase" time="0.015" classname="Framework.TestNG.TestNGBasics"/>
  <testcase name="testCase2" time="0.0" classname="Framework.TestNG.TestNGBasics"/>
  <testcase name="testTheLoginBtn" time="1.708" classname="Framework.TestNG.LoginTest"/>
  <testcase name="shoppingCartTest" time="2.55" classname="Framework.TestNG.Practice1"/>
  <testcase name="testLogIn" time="4.05" classname="Framework.TestNG.LoginTest">
    <failure type="java.lang.AssertionError" message="The app did not log in expected [My Account] but found [Account Login]">
      <![CDATA[java.lang.AssertionError: The app did not log in expected [My Account] but found [Account Login]
at Framework.TestNG.LoginTest.testLogIn(LoginTest.java:47)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testLogIn -->
  <testcase name="hpLaptop" time="5.692" classname="Framework.TestNG.Practice2"/>
  <testcase name="macBook" time="3.961" classname="Framework.TestNG.Practice2"/>
  <testcase name="loginScenario1" time="2.722" classname="Framework.TestNG.Practice1"/>
  <testcase name="loginScenario2" time="2.038" classname="Framework.TestNG.Practice1"/>
  <testcase name="loginScenario3" time="2.2" classname="Framework.TestNG.Practice1"/>
  <testcase name="loginScenario4" time="2.444" classname="Framework.TestNG.Practice1"/>
</testsuite> <!-- Chrome Test -->
